### ISSUE TITLE
Conflict between treesitter and Luasnip snippets for latex

### ISSUE THREAD

**Issue by jczhang02** [mathjiajia/config.nvim#4]
Hi, i have forked your snippets for a while. It seems like that treesitter(latex) is requested for the snippets. But your treesitter config do not include `latex` into ensure_installed. 

I do not want to use treesitter latex since it is slow, so i come here for your method.

Thanks!

**Comment by jczhang02** [comment]
[https://github.com/mathjiajia/config.nvim/blob/d917e46c90f17dfa49c397911d1ebd8e2d59d60e/lua/utils/latex.lua](url for the code)

**Comment by jczhang02** [comment]
[](https://github.com/mathjiajia/config.nvim/blob/d917e46c90f17dfa49c397911d1ebd8e2d59d60e/lua/utils/latex.lua)

**Comment by mathjiajia** [comment]
> But your treesitter config do not include `latex` into ensure_installed.

This is because, in a recent update of nvim-treesitter, it can install the parsers automatically.
For simplicity, I remove the `latex` from `ensure_installed`.

> I do not want to use treesitter latex since it is slow, so i come here for your method.

That's easy. I assume that you are using `vimtex`.
For all files in `nvim/luasnippets/tex` folder, replace
```lua
local tex = require 'utils.latex'
```
with below:
```lua
local tex = {}

tex.in_mathzone = function()
    return vim.fn["vimtex#syntax#in_mathzone"]() == 1
end

tex.in_comment = function()
    return vim.fn["vimtex#syntax#in_comment"]() == 1
end

tex.in_text = function()
    return not in_mathzone() and not in_comment()
end

tex.in_align = function()
    return vim.fn["vimtex#env#is_inside"]("align")[1] ~= 0
end
```

NOTE: I do not know how to detect `xymtrix` with `vimtex`.
So you need to remove the snippets
(1) `arrows.lua`:
```lua
s({ trig = 'rmap', name = 'rational map arrow', wordTrig = false }, {
        d(1, function()
                if not tex.in_xymatrix() then
                      return sn(nil, { t '\\dashrightarrow ' })
                else
                       return sn(nil, { t { '\\ar@{-->}[' }, i(1), t { ']' } })
                 end
         end),
}, { condition = tex.in_mathzone }),

s({ trig = 'emb', name = 'embeddeing map arrow', wordTrig = false }, {
         d(1, function()
                 if not tex.in_xymatrix() then
                       return sn(nil, { t '\\hookrightarrow ' })
                 else
                        return sn(nil, { t { '\\ar@{^{(}->}[' }, i(1), t { ']' } })
                  end
         end),
}, { condition = tex.in_mathzone })
```
and (2) `symbols.lua`:
```lua
s(
        { trig = 'ar', name = 'normal arrows' },
        { t '\\ar[', i(1), t ']' },
        { condition = tex.in_xymatrix }
),
```

PS: If there are any other problems, please let me know and we may have a discussion.

**Comment by jczhang02** [comment]
Thanks for your detailed answer!
